### PR TITLE
Create cgoCircle

### PR DESCRIPTION
**Pull request by drew161**
This script was copied from https://pymolwiki.org/index.php/CgoCircle on Sept. 23, 2024. It appears to have been authored by Jason Vertrees.

### CODE REVIEW

**Comment by pslacerda** [comment]
I think this script belongs to the wiki and shouldn't be included into this repository.

It's impossible to set the normal vector to fully specify the circle. Neither it draws parallel to the screen, rendering it unsuitable to plain figures.

**Comment by drew161** [comment]
Thanks for your quick response Pedro! I am writing some code that calls the cgoCircle function, so I was hoping we could make the cgoCircle script available within this repo.

I thought this would be okay because the wiki is covered by a blanket GNU license. However it's a Free Documentation License, rather than a GPL or something similar. I guess that makes things a bit unclear with this script.

If you think it is best to leave it out, that is fine by me.

**Comment by pslacerda** [comment]
You're welcome, Drew!

I'm not concerned about the script license because I think we can freely put in this repo (with a note about license and probable author). I'm more concerned about the generalization of the script, but may I be failing to understand its usefulness?

**Comment by drew161** [comment]
Ah, okay. Thanks for the clarification.

Yes, it would be helpful to be able to specify the normal vector. I get around this by rotating the object matrix. I previously used the cgoCircle function to draw a series of circles in PyMOL that outline an area of particular interest (see image below).

spherical_sector_ApG_F5

**Comment by pslacerda** [comment]
I'm still failing to understand the usefulness. How did you rotated the matrix without a previous alignment?

**Comment by drew161** [comment]
In my case, the usefulness of this application of cgoCircle is that it makes it easy to illustrate whether (or how often) an atom resides within a defined region. I used this approach in a previous study to visualize results from MD simulations (doi: 10.1021/acs.jpcb.1c06546).

I rotated the matrix using the rotate command to match the O5'-P bond vector with the normal vector of the circles.

**Comment by drew161** [comment]
Is your concern primarily that you don't want this repo to become crowded with scripts that won't ultimately be used much?

**Comment by pslacerda** [comment]
It was me that completely failed to initially grasp the usefulness of the script. Now I can imagine what you're doing. It would be useful to colour the circles with the occupancy (how often) of the atom?

And I sill didn't got how did you rotated without a previous alignment. It would be helpful (at least for me) if you list the commands here.

Note: I'm not owner of this repo, just maintainer. Please, rename the script to ends with `.py` and I'll merge. I'd also included a note at the beginning to say where it was extracted from.

**Comment by drew161** [comment]
Nice idea! Depending on the use, coloring the circles would help convey the data.

To answer your rotation question, let's consider the example pictured in my previous response above. Let's represent the O5' atom as point _P_₁ and the P atom as point _P_₂ with the vector pointing from P1 to P2 as _v_₁. The vector _v_₂ is orthogonal to _v_₁. The standard coordinate vector _e_₃, or [0,0,1], is orthogonal to the planes made by the cgoCircles. Let's also let the angle between vectors _v_₁ and _e_₃ be ɑ.

Then, the molecule shown above can be rotated about the O5' atom such that the O5'-P bond points towards and is orthogonal to the circles using the following command:

cmd.rotate(_v_₂, ɑ, camera=0, object='molecule', origin=_P_₁)

Here is an image of the molecule before the rotation.

spherical_sector_ApG_F5_before_rotation

A similar approach could have be used to rotate the molecule around the P atom. This would have made more sense... I'm not sure why I didn't do it that way. However, either way gets the job done.

Alright, I'll let you know once I make the small changes that you mentioned.

**Comment by drew161** [comment]
I've made the changes that you suggested.

**Comment by pslacerda** [comment]
Thank you, Drew!

**Pull request merged**
