### PR TITLE
add drawgridbox.py

### PR DESCRIPTION
**Pull request by CunliangGeng**
It should be correct this time :-)

### CODE REVIEW

**Comment by autodataming** [comment]
I written a script named gridbox.py in https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/gridbox.py.  how to put the script to the pymolwiki website?

**Comment by CunliangGeng** [comment]
Check here https://www.mediawiki.org/wiki/Help:Starting_a_new_page to create a new page on PyMOLWiki. Probably you could create a "GridBox" page.

I have created a page "http://pymolwiki.org/index.php/DrawGridBox".  The "drawgridbox.py" and "gridbox.py" have totally different functions and features, while the function of "gridbox.py" is similar to "http://pymolwiki.org/index.php/DrawBoundingBox".

**Comment by autodataming** [comment]
thank you very much

**Comment by autodataming** [comment]
I write the script for visualling the grid box by the gpf file of autogrid.  The box position is based on the coordinate of the box not based on the selection.

**Pull request merged**
