### PR TITLE
fix (#118) and (#130)

### PR DESCRIPTION
**Pull request by wadx2019**
I fixed issues #118 and #130 that led to the terrible usage experience of autodock_plugin in win10. Moreover, the new code has been tested successfully in several docking cases. So, please approve my PR. 

Much thanks.

### CODE REVIEW

**Comment by speleo3** [comment]
Hi @wadx2019 - Do you know anyone else who is using this plugin and can confirm that your fixes work?

**Comment by wadx2019** [comment]
Hi, @speleo3 . No, but I have tested the new version in both win10 and ubuntu platforms, and did not import any other python packages, even any other functions and classes.

**Comment by wadx2019** [comment]
Besides, only one .py file is updated. So I believe it can run successfully without any destruction on most platforms.

**Comment by speleo3** [comment]
OK thanks. Your changes seem pretty straightforward, so let's merge this.

**Pull request merged**
