### PR TITLE
Add Geo-measures plugin v.0.7

### PR DESCRIPTION
**Pull request by lkagami**
Please add Geo-measures plugin v.0.7. 
Thank you so much.
Luciano

### CODE REVIEW

**Comment by speleo3** [comment]
Thanks a lot for your contribution! The plugin looks good.

I'm thinking if there might be a better way to host a multi-file plugin like this, instead of a ZIP file. I think a separate repository might be best, like https://github.com/lkagami/geo_measure_pymol_plugin. Either owned by your account, or by @Pymol-Scripts, do you have a preference? See https://github.com/Pymol-Scripts/pymol2-demo-plugin as example for a dedicated repository for a single plugin.

**Comment by lkagami** [comment]
Hi speleo3,
I created the lkagami/geo_measures_pymol repository.  What should I do for it to appear in pymol plugin mananger? Thank you so much!!

**Comment by speleo3** [comment]
I've created a PyMOLWiki page for the plugin (feel free to improve it!):
https://pymolwiki.org/index.php/Geo_Measures_Plugin

Users should download the ZIP from there, then do "Plugin > Plugin Manager > Install New Plugin > Choose file...".

**Comment by lkagami** [comment]
Hi Thomas,
I did not receive the password.
Thanks again!

**Comment by lkagami** [comment]
Hi Thomas,
Sorry! I have not received the password yet.  I also searched for spam.  Password recovery also does not send to my email.  Please, could you change my email account for another?  lucianopkagami@hotmail.com
Thanks again!! Bests,

**Comment by lkagami** [comment]
Michelle helped me.
Thank you so much!
Bests,

**Pull request closed without merging**
