### PR TITLE
 Independent color and as_putty options for color_by_conservation.py

### PR DESCRIPTION
**Pull request by pslacerda**
Now the option color and as_putty works independent of each other.

### CODE REVIEW

**Comment by pslacerda** [comment]
Put your @JarrettSJohnson and @speleo3 as reviewers because I don't know if I can accept my own PR.

**Comment by speleo3** [comment]
Why did you remove the `_self` argument? It's key for using [pymol2.PyMOL](https://github.com/schrodinger/pymol-open-source/tree/master/modules/pymol2) instances. See the [tests](https://github.com/schrodinger/pymol-open-source/blob/master/testing/tests/api/pymol2api.py) for usage examples.

**Comment by pslacerda** [comment]
It was my fault.

This `cmd` reference should be changed to `_self`?

https://github.com/Pymol-Scripts/Pymol-script-repo/blob/1cb0eaff867c988b97d33a695290c48dea56117e/color_by_conservation.py#L30

**Comment by speleo3** [comment]
> This cmd reference should be changed to _self?

Yes

**Comment by pslacerda** [comment]
Done.

**Review by speleo3 — APPROVED** [review]
LGTM

**Pull request merged**
